<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ALAJUELAALAJUELA RURALBARRANCABELENB_01f2a5</name>
   <tag></tag>
   <elementGuidId>e9872c28-6c77-4fd1-8934-d20150a4e4d3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0022W0008W0007PLANCOMERCIALSUCURSAL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0022W0008W0007PLANCOMERCIALSUCURSAL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 36,'W0022W0008W0007',false,'',0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.evt.onchange(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>gx.num.valid_integer( this,'.');;gx.evt.onblur(36);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gxvalid</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
ALAJUELAALAJUELA RURALBARRANCABELENBELEN RURALCALL CENTERCARTAGENACARTAGOCARTAGO RURALCHACARITACOBROSCOMUNIDADCOMUNIDAD RURALCURRIDABATDIGITACION CURRIDABATDIGITACION SABANADTH PACIFICO NORTEDTH PACIFICO SURDTH ZONA ATLANTICADTH ZONA NORTEEL COCOEL COCO RURALEL ROBLEEL ROBLE RURALESPARZAESPARZA RURALFILADELFIAFILADELFIA RURALGRECIAGRECIA RURALGUAPILESGUAPILES RURALHEREDIAHEREDIA RURALHUACASITSLA SABANALA SABANA RURALLIBERIALIBERIA-LIBERIAMIRAMARMORAVIANARANJONARANJO RURALNICOYANICOYA RURALPAGO EN LINEAPARAISOPARRITAPARRITA-PARRITAPASEO DE LAS FLORESPAVASPUNTARENASQUEPOSQUEPOS RURALRECSASAMARASAN MARCOSSAN MARCOS RURALSAN PABLOSAN PEDROSAN PEDRO DE POASSAN RAMONSAN RAMON RURALSANTA BARBARASANTA CRUZSANTA CRUZ RURALSANTA MARIASARCHISARDINALSARDINAL RURALSIQUIRRESSIQUIRRES RURALSTPTAMARINDOTAMARINDO RURALTELEMARKETINGTURRIALBATURRIALBA RURAL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0022W0008W0007PLANCOMERCIALSUCURSAL&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0022W0008W0007PLANCOMERCIALSUCURSAL']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='W0022W0008W0007TABLE2']/tbody/tr[4]/td[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sucursal'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLAN PRUEBA'])[2]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
