<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TERMINAL PRUEBA</name>
   <tag></tag>
   <elementGuidId>d21846d2-d3fe-402e-9067-49f5ba198316</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='span_TERMINALDSC_0001']/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;span_TERMINALDSC_0001&quot;)/a[1][count(. | //*[(text() = 'TERMINAL PRUEBA' or . = 'TERMINAL PRUEBA') and @ref_element = 'Object Repository/Page_Terminales de la Oficina/iframe_Seleccionar Terminal de cobro (POS)__127cba']) = count(//*[(text() = 'TERMINAL PRUEBA' or . = 'TERMINAL PRUEBA') and @ref_element = 'Object Repository/Page_Terminales de la Oficina/iframe_Seleccionar Terminal de cobro (POS)__127cba'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:gx.popup.gxReturn(['0654662356']);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TERMINAL PRUEBA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;span_TERMINALDSC_0001&quot;)/a[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Terminales de la Oficina/iframe_Seleccionar Terminal de cobro (POS)__127cba</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_TERMINALDSC_0001']/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'TERMINAL PRUEBA')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, &quot;javascript:gx.popup.gxReturn(['0654662356']);&quot;)])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span/a</value>
   </webElementXpaths>
</WebElementEntity>
