<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_1EFECTIVOCHEQUETARJETADEPOSITODEBITOONLI_d86239</name>
   <tag></tag>
   <elementGuidId>44e60c23-371f-40c5-aac6-8b10ef863911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RecibolineagridContainerRow_0001</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='RecibolineagridContainerRow_0001']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RecibolineagridContainerRow_0001</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxrow</name>
      <type>Main</type>
      <value>0001</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Grid_WorkWithOdd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  1EFECTIVOCHEQUETARJETADEPOSITODEBITOONLINEE-PAGOS AMSYSE-PAGOS CLIENTES EXTERNOSE-VALORES RECIBIDOS OTRAS OF.E-VENTAS PUBLICIDADE-VENTAS ARTÍCULOSE-OTROS INGRESOSE-FALTANTES CAJA &lt; 1000E-FALTANTES CAJA > 1000E-SOBRANTES CAJA > 1000E-SOBRANTES CAJA &lt; 1000E-COMISIONESE-OTROS PENDIENTESE-DIFERENCIAL CAMBIARIO (+)E-DIFERENCIAL CAMBIARIO (-)E-COMISIONES PAGADASE-OTROS FALTANTESE-OTROS SOBRANTESCOMISIONES BANCARIASAJUSTE CONVENIO AVALDEPOSITOS DE MASDEVOLUCION DE DEPOSITOSPAGO DE MAS TARJETASPAGO EN LINEAREDONDEO NEGATIVOREDONDEO POSITIVOE-DEVOLUCION DE DEPOSITOSE-DEPOSITOS DE MASE-PAGO EN LINEAE-REDONDEO NEGATIVOE-REDONDEO POSITIVOE-PAGO DE MAS TARJETASE-AJUSTE CONVENIO AVALE-COMISIONES BANCARIASD-PAGOS AMSYSD-PAGOS CLIENTES EXTERNOSD-VALORES RECIBIDOS OTRAS OF.D-VENTAS PUBLICIDADD-VENTAS ARTÍCULOSD-OTROS INGRESOSD-FALTANTES CAJA &lt; 1000D-FALTANTES CAJA > 1000D-SOBRANTES CAJA > 1000D-SOBRANTES CAJA &lt; 1000D-COMISIONESD-OTROS PENDIENTESD-DIFERENCIAL CAMBIARIO (+)D-DIFERENCIAL CAMBIARIO (-)D-COMISIONES PAGADASD-OTROS FALTANTESD-OTROS SOBRANTESD-DEVOLUCION DE DEPOSITOSD-DEPOSITOS DE MASD-PAGO EN LINEAD-REDONDEO NEGATIVOD-REDONDEO POSITIVOD-PAGO DE MAS TARJETASCONTRACARGOS TARJETASD-COMISIONES BANCARIASAJUSTE TARJETACOMISIONESCHEQUE DEVOLUCIÓNTRANSFERENCIARETENCIONESIVA POR COMISIÓNEFECTIVO¢T/C0,000    45821,90    45821,90CuentaCSLote/DepósitoAutorizaciónC.PostalVencimiento  /  /    Horas0     0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RecibolineagridContainerRow_0001&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//tr[@id='RecibolineagridContainerRow_0001']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='RecibolineagridContainerTbl']/tbody/tr</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DNI'])[1]/following::tr[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CUIT'])[1]/following::tr[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/div/table/tbody/tr</value>
   </webElementXpaths>
</WebElementEntity>
