<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LISTA300 SERVICIOMEG10 PAQUETEDP10Z</name>
   <tag></tag>
   <elementGuidId>8679c0c4-a570-4887-9f5d-cec52a051f17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='span_vGPOLITICANOMBRE_0001']/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;span_vGPOLITICANOMBRE_0001&quot;)/a[1][count(. | //*[(text() = 'LISTA:300 SERVICIO:MEG10 PAQUETE:DP10Z' or . = 'LISTA:300 SERVICIO:MEG10 PAQUETE:DP10Z') and @ref_element = 'Object Repository/Page_Plan Comercial Item/iframe_Seleccionar Producto Politica_gxp0_ifrm_1_2']) = count(//*[(text() = 'LISTA:300 SERVICIO:MEG10 PAQUETE:DP10Z' or . = 'LISTA:300 SERVICIO:MEG10 PAQUETE:DP10Z') and @ref_element = 'Object Repository/Page_Plan Comercial Item/iframe_Seleccionar Producto Politica_gxp0_ifrm_1_2'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:gx.popup.gxReturn(['5217']);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LISTA:300 SERVICIO:MEG10 PAQUETE:DP10Z</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;span_vGPOLITICANOMBRE_0001&quot;)/a[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Plan Comercial Item/iframe_Seleccionar Producto Politica_gxp0_ifrm_1_2</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_vGPOLITICANOMBRE_0001']/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:gx.popup.gxReturn(['5217']);&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
   </webElementXpaths>
</WebElementEntity>
