<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BANCO DE COSTA RICA</name>
   <tag></tag>
   <elementGuidId>be757412-d0d1-4b3f-ba7e-99ffc41d2c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='span_BANCONOMBRE_0002']/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;span_BANCONOMBRE_0002&quot;)/a[1][count(. | //*[(text() = 'BANCO DE COSTA RICA' or . = 'BANCO DE COSTA RICA') and @ref_element = 'Object Repository/Page_Cuentas bancarias de una oficina/iframe_Seleccionar Banco de la empresa_gxp0_ifrm']) = count(//*[(text() = 'BANCO DE COSTA RICA' or . = 'BANCO DE COSTA RICA') and @ref_element = 'Object Repository/Page_Cuentas bancarias de una oficina/iframe_Seleccionar Banco de la empresa_gxp0_ifrm'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:gx.popup.gxReturn(['2']);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BANCO DE COSTA RICA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;span_BANCONOMBRE_0002&quot;)/a[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Cuentas bancarias de una oficina/iframe_Seleccionar Banco de la empresa_gxp0_ifrm</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_BANCONOMBRE_0002']/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BANCO DE COSTA RICA')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:gx.popup.gxReturn(['2']);&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/span/a</value>
   </webElementXpaths>
</WebElementEntity>
