<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BCR Colones</name>
   <tag></tag>
   <elementGuidId>ddb8745f-57bc-432f-8c80-45fc80280600</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='span_BANCOCUENTANOMBRE_0001']/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;span_BANCOCUENTANOMBRE_0001&quot;)/a[1][count(. | //*[(text() = 'BCR Colones' or . = 'BCR Colones') and @ref_element = 'Object Repository/Page_Cuentas bancarias de una oficina/iframe_Seleccionar Empresa Cuenta Bancaria__d686e4']) = count(//*[(text() = 'BCR Colones' or . = 'BCR Colones') and @ref_element = 'Object Repository/Page_Cuentas bancarias de una oficina/iframe_Seleccionar Empresa Cuenta Bancaria__d686e4'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:gx.popup.gxReturn(['204183-9']);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BCR Colones</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;span_BANCOCUENTANOMBRE_0001&quot;)/a[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Cuentas bancarias de una oficina/iframe_Seleccionar Empresa Cuenta Bancaria__d686e4</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_BANCOCUENTANOMBRE_0001']/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BCR Colones')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/span/a</value>
   </webElementXpaths>
</WebElementEntity>
