<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Ninguno)BASICO-ONE TV ELITE  200MB _3f6a69</name>
   <tag></tag>
   <elementGuidId>f9464f2e-73db-410d-b847-51963f1eb1aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vE_POLITICAID_0001</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='vE_POLITICAID_0001']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'vE_POLITICAID_0001' and @name = 'vE_POLITICAID_0001' and (text() = '(Ninguno)BASICO-ONE TV ELITE + 200MB MIGRACION V2BASICO-ONE TV ELITE + 200MB MIGRACIONBASICO- ONE TV ELITE + 150MB MIGRACIONTV - TV DIGITAL + 100 MBTV - TV DIGITAL + 50 MB (EQUIPO + SERVICIOTV - TV DIGITAL + 30 MBAUTOCONSUMO- SERVICIO BASICOSERVICIO BASICO CM-TV DIGITAL (MIGRACION)BASICO -  PLAN EMPLEADO ONE TV  DVR + 100MBBASICO -  PLAN EMPLEADO ONE TV DVR + 75MBBASICO -  PLAN EMPLEADO ONE TV + 100MBBASICO - PLAN EMPLEADO ONE TV + 75MBBASICO - PLAN EMPLEADO TV HD + 50MBBASICO - PLAN EMPLEADO TV HD + 15MBSERVICIO BASICO TV-PLAN-1186SERVICIO BASICO ONE TV  (38HD) + 30MBSERVICIO BASICO - ONE TV LITE DVR (40HD) + 30MBSERVICIO BASICO - TVHD + 50MBSERVICIO BASICO - TVHD DVB + 30MBSERVICIO BASICO - TVHD + 30MBSERVICIO BASICO - TVHD + 20MBSERVICIO BASICO - TV DVB HD + 20MBSERVICIO BASICO - TV DVB + 20MBSERVICIO BASICO - TV DIGITAL + 30MBSERVICIO BASICO - ONE ELITE + 100MBSERVICIO BASICO - ONE TV ELITE + 75MBSERVICIO BASICO - ONE TV ELITE + 50MBSERVICIO BASICO - ONE TV DVR (16HD) + 30MBSERVICIO BASICO - ONE TV (16HD) + 30MBSERVICIO BASICO - ONE TV FULL (40HD) + 15MBSERVICIO BASICO - ONE TV LITE DVR (6HD) + 8MBSERVICIO BASICO - ONE TV LITE (6HD) +8MBSERVICIO BASICO-2017 DIGITAL NEW BASIC  RURALSERVICIO BASICO-2017 DIGITAL NEW BASIC  GAMSERVICIO BASICO - TV DIGITAL + 2MB GAM V2TV BASICO - TV DIG HD+ 15MB GAMSERVICIO BASICO - HD + 15MB GAMSERVICIO BASICO - DIG AVANZADO + 15 RURALSERVICIO BASICO - DIG AVANZADO + 15 GAMVS SERVICIO BASICO TV VALLE DEL SOLTV BASICO ESPECIAL GAM #3TV BASICO ESPECIAL RURAL #2TV BASICO ESPECIAL GAM #2TV BASICO ESPECIAL RURAL #1BASIC -- INQUILINO UHM GAM -- ATERRIZADOBASIC-- HOTEL O UHM -- ATERRIZADOBASIC -- SERVICIO BASICO RURAL PARRITABASIC-- SERVICIO BASICO RURALBASIC --INQUILINO UHM GAMBASIC -- SERVICIO BASICO GAM Y LIBERIA' or . = '(Ninguno)BASICO-ONE TV ELITE + 200MB MIGRACION V2BASICO-ONE TV ELITE + 200MB MIGRACIONBASICO- ONE TV ELITE + 150MB MIGRACIONTV - TV DIGITAL + 100 MBTV - TV DIGITAL + 50 MB (EQUIPO + SERVICIOTV - TV DIGITAL + 30 MBAUTOCONSUMO- SERVICIO BASICOSERVICIO BASICO CM-TV DIGITAL (MIGRACION)BASICO -  PLAN EMPLEADO ONE TV  DVR + 100MBBASICO -  PLAN EMPLEADO ONE TV DVR + 75MBBASICO -  PLAN EMPLEADO ONE TV + 100MBBASICO - PLAN EMPLEADO ONE TV + 75MBBASICO - PLAN EMPLEADO TV HD + 50MBBASICO - PLAN EMPLEADO TV HD + 15MBSERVICIO BASICO TV-PLAN-1186SERVICIO BASICO ONE TV  (38HD) + 30MBSERVICIO BASICO - ONE TV LITE DVR (40HD) + 30MBSERVICIO BASICO - TVHD + 50MBSERVICIO BASICO - TVHD DVB + 30MBSERVICIO BASICO - TVHD + 30MBSERVICIO BASICO - TVHD + 20MBSERVICIO BASICO - TV DVB HD + 20MBSERVICIO BASICO - TV DVB + 20MBSERVICIO BASICO - TV DIGITAL + 30MBSERVICIO BASICO - ONE ELITE + 100MBSERVICIO BASICO - ONE TV ELITE + 75MBSERVICIO BASICO - ONE TV ELITE + 50MBSERVICIO BASICO - ONE TV DVR (16HD) + 30MBSERVICIO BASICO - ONE TV (16HD) + 30MBSERVICIO BASICO - ONE TV FULL (40HD) + 15MBSERVICIO BASICO - ONE TV LITE DVR (6HD) + 8MBSERVICIO BASICO - ONE TV LITE (6HD) +8MBSERVICIO BASICO-2017 DIGITAL NEW BASIC  RURALSERVICIO BASICO-2017 DIGITAL NEW BASIC  GAMSERVICIO BASICO - TV DIGITAL + 2MB GAM V2TV BASICO - TV DIG HD+ 15MB GAMSERVICIO BASICO - HD + 15MB GAMSERVICIO BASICO - DIG AVANZADO + 15 RURALSERVICIO BASICO - DIG AVANZADO + 15 GAMVS SERVICIO BASICO TV VALLE DEL SOLTV BASICO ESPECIAL GAM #3TV BASICO ESPECIAL RURAL #2TV BASICO ESPECIAL GAM #2TV BASICO ESPECIAL RURAL #1BASIC -- INQUILINO UHM GAM -- ATERRIZADOBASIC-- HOTEL O UHM -- ATERRIZADOBASIC -- SERVICIO BASICO RURAL PARRITABASIC-- SERVICIO BASICO RURALBASIC --INQUILINO UHM GAMBASIC -- SERVICIO BASICO GAM Y LIBERIA')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vE_POLITICAID_0001</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vE_POLITICAID_0001</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Grid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 89,'',false,'0001',67)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.evt.onchange(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,89);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gxoch0</name>
      <type>Main</type>
      <value>if( gx.evt.jsEvent(this)) {gx.evt.execEvt('',false,'EVE_POLITICAID.CLICK.0001',this,67);} else return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(Ninguno)BASICO-ONE TV ELITE + 200MB MIGRACION V2BASICO-ONE TV ELITE + 200MB MIGRACIONBASICO- ONE TV ELITE + 150MB MIGRACIONTV - TV DIGITAL + 100 MBTV - TV DIGITAL + 50 MB (EQUIPO + SERVICIOTV - TV DIGITAL + 30 MBAUTOCONSUMO- SERVICIO BASICOSERVICIO BASICO CM-TV DIGITAL (MIGRACION)BASICO -  PLAN EMPLEADO ONE TV  DVR + 100MBBASICO -  PLAN EMPLEADO ONE TV DVR + 75MBBASICO -  PLAN EMPLEADO ONE TV + 100MBBASICO - PLAN EMPLEADO ONE TV + 75MBBASICO - PLAN EMPLEADO TV HD + 50MBBASICO - PLAN EMPLEADO TV HD + 15MBSERVICIO BASICO TV-PLAN-1186SERVICIO BASICO ONE TV  (38HD) + 30MBSERVICIO BASICO - ONE TV LITE DVR (40HD) + 30MBSERVICIO BASICO - TVHD + 50MBSERVICIO BASICO - TVHD DVB + 30MBSERVICIO BASICO - TVHD + 30MBSERVICIO BASICO - TVHD + 20MBSERVICIO BASICO - TV DVB HD + 20MBSERVICIO BASICO - TV DVB + 20MBSERVICIO BASICO - TV DIGITAL + 30MBSERVICIO BASICO - ONE ELITE + 100MBSERVICIO BASICO - ONE TV ELITE + 75MBSERVICIO BASICO - ONE TV ELITE + 50MBSERVICIO BASICO - ONE TV DVR (16HD) + 30MBSERVICIO BASICO - ONE TV (16HD) + 30MBSERVICIO BASICO - ONE TV FULL (40HD) + 15MBSERVICIO BASICO - ONE TV LITE DVR (6HD) + 8MBSERVICIO BASICO - ONE TV LITE (6HD) +8MBSERVICIO BASICO-2017 DIGITAL NEW BASIC  RURALSERVICIO BASICO-2017 DIGITAL NEW BASIC  GAMSERVICIO BASICO - TV DIGITAL + 2MB GAM V2TV BASICO - TV DIG HD+ 15MB GAMSERVICIO BASICO - HD + 15MB GAMSERVICIO BASICO - DIG AVANZADO + 15 RURALSERVICIO BASICO - DIG AVANZADO + 15 GAMVS SERVICIO BASICO TV VALLE DEL SOLTV BASICO ESPECIAL GAM #3TV BASICO ESPECIAL RURAL #2TV BASICO ESPECIAL GAM #2TV BASICO ESPECIAL RURAL #1BASIC -- INQUILINO UHM GAM -- ATERRIZADOBASIC-- HOTEL O UHM -- ATERRIZADOBASIC -- SERVICIO BASICO RURAL PARRITABASIC-- SERVICIO BASICO RURALBASIC --INQUILINO UHM GAMBASIC -- SERVICIO BASICO GAM Y LIBERIA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vE_POLITICAID_0001&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='vE_POLITICAID_0001']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='GridproductosContainerRow_0001']/td[22]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BASICO'])[1]/following::select[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B'])[1]/following::select[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMUN'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¢'])[3]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[22]/select</value>
   </webElementXpaths>
</WebElementEntity>
