<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ALMACEN DESECHO TIGOALMACEN WODENART_7657fe</name>
   <tag></tag>
   <elementGuidId>15f8ded0-c519-4066-a42e-29332107874c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0022W0008W0007CENTROSTOCKDESID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0022W0008W0007CENTROSTOCKDESID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 28,'W0022W0008W0007',false,'',0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.evt.onchange(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>gx.num.valid_integer( this,'.');;gx.evt.onblur(28);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gxvalid</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
ALMACEN DESECHO TIGO
ALMACEN WODEN
ARTICULO NUEVO
AYB (DEPOSITO)
AYB (MOVIL)
BODEGA ARENAL
BODEGA DEVOLUCION LUVITILSE
BODEGA DEVOLUCION LUVITILSE CURRIDABAT
BODEGA DEVOLUCION LUVITILSE GUAPILES
BODEGA DEVOLUCION LUVITILSE PAVAS
BODEGA DEVOLUCION MARACEL
BODEGA DEVOLUCION MARACEL LIBERIA
BODEGA DEVOLUCION MARACEL NICOYA
BODEGA DEVOLUCION MARACEL PEREZ ZELEDON
BODEGA DEVOLUCION MARACEL PUNTARENAS
BODEGA DEVOLUCION MARACEL RIO CLARO
BODEGA DEVOLUCION MARACEL SANTA ANA
BODEGA DEVOLUCION MYM
BODEGA DEVOLUCION OFICINAS NO INTERES
BODEGA DEVOLUCION OFICINAS WODEN
BODEGA DEVOLUCION SERVITEC
BODEGA DEVOLUCION SERVITELECOM JMG
BODEGA DEVOLUCION SETEO
BODEGA DEVOLUCION SETEO CARTAGO
BODEGA DEVOLUCION SETEO GUATUSO
BODEGA DEVOLUCION SETEO HEREDIA
BODEGA DEVOLUCION SETEO LIMON
BODEGA DEVOLUCION SETEO PALMARES
BODEGA DEVOLUCION SWAT SUP
BODEGA DEVOLUCION TECNISERVICIOS
BODEGA DISERVSA
BODEGA EQUIPO RECUPERADO
BODEGA EQUIPO SCRAP
BODEGA EQUIPOS NO RECUPERABLES
BODEGA EQUIPOS RECUPERADOS
BODEGA GREEN HOME RECUPERO DTH
BODEGA GREEN HOME RECUPERO HFC
BODEGA JMG SERVITELECOM
BODEGA LUVITILSE CURRIDABAT
BODEGA LUVITILSE GUAPILES
BODEGA LUVITILSE PAVAS
BODEGA LUVITILSE TURRIALBA
BODEGA MARACEL LIBERIA
BODEGA MARACEL NICOYA
BODEGA MARACEL PUNTARENAS
BODEGA MARACEL PZ
BODEGA MARACEL RIO CLARO
BODEGA MARACEL SANTA ANA
BODEGA RETENCION HVC/NGTV
BODEGA RETENCIÓN
BODEGA SERVITELECOM JMG
BODEGA SETEO ALAJUELA
BODEGA SETEO CARTAGO
BODEGA SETEO GUATUSO
BODEGA SETEO HEREDIA
BODEGA SETEO LIBERIA
BODEGA SETEO LIMÓN
BODEGA SETEO NARANJO
BODEGA SETEO SABANA
BODEGA SOLFINSUR
BODEGA SWAT SUP
BODEGA TECNISERVICIOS EL ROBLE
BODEGA TECNISERVICIOS GUANACASTE
BODEGA TIGO
BODEGA TIGO TRANSITORIA CONTRATISTAS
BODEGA TIGO TRANSITORIA FRONTDESK
BODEGA TRANSITORIA GREEN HOME RECUPERO
BODEGA TRANSITORIA LIMPIEZA
BODEGA TRANSITORIA MYM RECUPERO
BODEGA TRUE SALES
BODEGAS CABLE MAX
BODEGAS KYM
BODEGAS LUVITILSE
BODEGAS LUVITILSE USADOS
BODEGAS MARACEL
BODEGAS MARACEL USADOS
BODEGAS MYM
BODEGAS SERVITEC
BODEGAS SETEO
BODEGAS SETEO USADOS
BODEGAS ST REDES
BODEGAS SWAT SUP USADOS
BODEGAS TECNISERVICIOS
COBROS NO PAGO TRANSITORIO
DEPOSITO MOVILES KALEB CASTO S.A
DIAGNOSTICO NIVEL 2
DISERVSA (MOVILES)
DISERVSA MOVIL DISER-01
DISERVSA MOVIL DISER-02
DISERVSA MOVIL DISER-03
DISERVSA MOVIL DISER-04
DTH KYM (MOVILES)
DTH MARACEL (MOVILES)
DTH SERVITELECOM JMG (MOVILES)
DTH SETEO (MOVILES)
DTH SOLFINSUR (MOVILES)
DTH TECNISERVICIOS (MOVILES)
DTH TRUE SALES (MOVILES)
EQUIPO COBRADO AL CLIENTE
FRONTDESK ALAJUELA
FRONTDESK CARTAGO
FRONTDESK CAÑAS (CABLEMAX)
FRONTDESK CURRIDABAT
FRONTDESK DEVOLUCION CAÑAS
FRONTDESK DEVOLUCION CAÑAS (CABLEMAX)
FRONTDESK DEVOLUCION PEREZ ZELEDON
FRONTDESK DEVOLUCION TILARAN
FRONTDESK DEVOLUCION TILARAN (CABLEMAX)
FRONTDESK DEVOLUCIÓN ALAJUELA
FRONTDESK DEVOLUCIÓN CARTAGO
FRONTDESK DEVOLUCIÓN CURRIDABAT
FRONTDESK DEVOLUCIÓN EL COCO
FRONTDESK DEVOLUCIÓN EL ROBLE
FRONTDESK DEVOLUCIÓN GRECIA
FRONTDESK DEVOLUCIÓN GUAPILES
FRONTDESK DEVOLUCIÓN HEREDIA
FRONTDESK DEVOLUCIÓN LIBERIA
FRONTDESK DEVOLUCIÓN NARANJO
FRONTDESK DEVOLUCIÓN NICOYA
FRONTDESK DEVOLUCIÓN QUEPOS
FRONTDESK DEVOLUCIÓN SABANA REAL
FRONTDESK DEVOLUCIÓN SAN RAMON
FRONTDESK DEVOLUCIÓN SANTA CRUZ
FRONTDESK DEVOLUCIÓN TAMARINDO
FRONTDESK DEVOLUCIÓN TURRIALBA
FRONTDESK EL COCO
FRONTDESK EL ROBLE
FRONTDESK GRECIA
FRONTDESK GUAPILES
FRONTDESK HEREDIA
FRONTDESK HOGARES CONECTADOS
FRONTDESK LIBERIA
FRONTDESK NARANJO
FRONTDESK NICOYA
FRONTDESK NO FISICO ALAJUELA
FRONTDESK NO FISICO CARTAGO
FRONTDESK NO FISICO CAÑAS (CABLE MAX)
FRONTDESK NO FISICO EL COCO
FRONTDESK NO FISICO EL ROBLE
FRONTDESK NO FISICO GRECIA
FRONTDESK NO FISICO GUAPILES
FRONTDESK NO FISICO HEREDIA
FRONTDESK NO FISICO LIBERIA
FRONTDESK NO FISICO PEREZ ZELEDON
FRONTDESK NO FISICO SABANA
FRONTDESK NO FISICO SAN PEDRO
FRONTDESK NO FISICO SAN RAMON
FRONTDESK NO FISICO SANTA CRUZ
FRONTDESK NO FISICO TURRIALBA
FRONTDESK PEREZ ZELEDON
FRONTDESK QUEPOS
FRONTDESK SABANA REAL
FRONTDESK SAN RAMON
FRONTDESK SANTA CRUZ
FRONTDESK TAMARINDO
FRONTDESK TILARAN (CABLEMAX)
FRONTDESK TURRIALBA
GRUPO SIC (DEPOSITO)
GRUPO SIC (MOVIL)
GRUPO TENT (DEPOSITO)
GRUPO TENT (MOVIL)
INSAT MOVIL-01
INSAT MOVIL-02
INSAT MOVIL-03
INSAT MOVIL-04
KYM (MOVILES)
KYM MOVIL KM-01 
KYM MOVIL KM-02 
KYM MOVIL KM-02 
KYM MOVIL KM-03
KYM MOVIL KM-03
KYM MOVIL KM-04 
KYM MOVIL KM-05
KYM MOVIL KM-06
KYM MOVIL KM-07
KYM MOVIL KM-08
KYM MOVIL KM-09 
KYM MOVIL KM-10
KYM MOVIL KM-11
KYM MOVIL KM-12 
KYM MOVIL KM-13
KYM MOVIL KM-14
KYM MOVIL KM-15
KYM MOVIL KM-16
KYM MOVIL KM-17
KYM MOVIL KM-18
KYM MOVIL KM-19
KYM MOVIL KM-20
KYM MOVIL KM-21
KYM MOVIL KM-22
KYM MOVIL KM-23
KYM MOVIL KM-24
KYM MOVIL KM-25
KYM MOVIL KM-26
KYM MOVIL KM-27
KYM MOVIL KM-28
LUVITILSE (MOVILES)
LUVITILSE EQUIPO NO UTILIZABLE
LUVITILSE EQUIPOS RACSA
LUVITILSE M SUP 1
LUVITILSE M SUP 2
LUVITILSE M SUP 3
LUVITILSE M SUP 4
LUVITILSE M SUP 5
LUVITILSE M SUP 6
LUVITILSE M1
LUVITILSE M10
LUVITILSE M11
LUVITILSE M12
LUVITILSE M13
LUVITILSE M14
LUVITILSE M15
LUVITILSE M16
LUVITILSE M17
LUVITILSE M18
LUVITILSE M19
LUVITILSE M2
LUVITILSE M20
LUVITILSE M21
LUVITILSE M22
LUVITILSE M23
LUVITILSE M24
LUVITILSE M25
LUVITILSE M26
LUVITILSE M27
LUVITILSE M28
LUVITILSE M29
LUVITILSE M3
LUVITILSE M30
LUVITILSE M31
LUVITILSE M32
LUVITILSE M33
LUVITILSE M34
LUVITILSE M35
LUVITILSE M36
LUVITILSE M37
LUVITILSE M38
LUVITILSE M39
LUVITILSE M4
LUVITILSE M40
LUVITILSE M41
LUVITILSE M42
LUVITILSE M43
LUVITILSE M44
LUVITILSE M45
LUVITILSE M46
LUVITILSE M47
LUVITILSE M48
LUVITILSE M49
LUVITILSE M5
LUVITILSE M50
LUVITILSE M51
LUVITILSE M52
LUVITILSE M53
LUVITILSE M54
LUVITILSE M55
LUVITILSE M56
LUVITILSE M57
LUVITILSE M58
LUVITILSE M59
LUVITILSE M6
LUVITILSE M60
LUVITILSE M61
LUVITILSE M62
LUVITILSE M63
LUVITILSE M64
LUVITILSE M65
LUVITILSE M66
LUVITILSE M67
LUVITILSE M68
LUVITILSE M69
LUVITILSE M7
LUVITILSE M70
LUVITILSE M71
LUVITILSE M72
LUVITILSE M73
LUVITILSE M74
LUVITILSE M75
LUVITILSE M76
LUVITILSE M77
LUVITILSE M78
LUVITILSE M79
LUVITILSE M8
LUVITILSE M9
LUVITILSE MOVIL L-01
LUVITILSE MOVIL L-02
LUVITILSE MOVIL L-02
LUVITILSE MOVIL L-03
LUVITILSE MOVIL L-03
LUVITILSE MOVIL L-04
LUVITILSE MOVIL L-07
LUVITILSE MOVIL L-08
LUVITILSE MOVIL L-09
LUVITILSE MOVIL L-10
LUVITILSE MOVIL L-11
LUVITILSE MOVIL L-12
LUVITILSE MOVIL L-13
LUVITILSE MOVIL L-14
LUVITILSE MOVIL L-15
LUVITILSE MOVIL L-17
LUVITILSE MOVIL L-18
LUVITILSE MOVIL L-19
LUVITILSE MOVIL L-20
LUVITILSE MOVIL L-21
LUVITILSE MOVIL L-23
LUVITILSE MOVIL L-24
LUVITILSE MOVIL L-26
LUVITILSE MOVIL L-27
LUVITILSE MOVIL L-28
LUVITILSE MOVIL L-30
LUVITILSE MOVIL L-31
LUVITILSE MOVIL L-40
LUVITILSE MOVIL L-41
LUVITILSE MOVIL L-42
LUVITILSE MOVIL L-43
LUVITILSE MOVIL L-44
LUVITILSE MOVIL L-45
LUVITILSE MOVIL L-46
LUVITILSE MOVIL L-47
MARACEL EQUIPO NO UTILIZABLE
MARACEL M SUP1
MARACEL M SUP2
MARACEL M SUP3
MARACEL M SUP4
MARACEL M1
MARACEL M10
MARACEL M11
MARACEL M12
MARACEL M13
MARACEL M14
MARACEL M15
MARACEL M16
MARACEL M17
MARACEL M18
MARACEL M19
MARACEL M2
MARACEL M20
MARACEL M21
MARACEL M22
MARACEL M23
MARACEL M24
MARACEL M25
MARACEL M26
MARACEL M27
MARACEL M3
MARACEL M4
MARACEL M5
MARACEL M6
MARACEL M7
MARACEL M8
MARACEL M9
MARACEL MH1
MARACEL MH10
MARACEL MH11
MARACEL MH12
MARACEL MH13
MARACEL MH14
MARACEL MH15
MARACEL MH16
MARACEL MH17
MARACEL MH18
MARACEL MH19
MARACEL MH2
MARACEL MH20
MARACEL MH21
MARACEL MH22
MARACEL MH23
MARACEL MH24
MARACEL MH25
MARACEL MH26
MARACEL MH27
MARACEL MH28
MARACEL MH29
MARACEL MH3
MARACEL MH30
MARACEL MH31
MARACEL MH32
MARACEL MH33
MARACEL MH34
MARACEL MH4
MARACEL MH5
MARACEL MH6
MARACEL MH7
MARACEL MH8
MARACEL MH9
MARACEL( MOVILES)
MOVILES JMG SERVITELECOM
MOVILES KALEB CASTO S.A
MOVILES RECUPERO B2C
MOVILES RECUPERO CTVS
MOVILES RECUPERO GREEN HOME
MOVILES RECUPERO LUVITILSE
MOVILES RECUPERO MYM
MOVILES RECUPERO SERVITEC
MOVILES RECUPERO SERVITELECOM JMG
MOVILES RECUPERO SETEO
MOVILES RECUPERO TECNISERVICIOS
MOVILES RECUPERO WODEN
MOVILES TODOS SUBCONTRATOS TODOS APROV
MOVILES TODOS SUBCONTRATOS TODOS DESAPROV	
MYM (MOVILES)
MYM EQUIPOS RACSA
MYM M SUP 54
MYM M SUP 55
MYM M10
MYM M11
MYM M12
MYM M13
MYM M14
MYM M15
MYM M16
MYM M17
MYM M18
MYM M19
MYM M20
MYM M21
MYM M22
MYM M23
MYM M24
MYM M25
MYM M26
MYM M27
MYM M28
MYM M29
MYM M30
MYM M31
MYM M32
MYM M33
MYM M34
MYM M35
MYM M36
MYM M37
MYM M38
MYM M39
MYM M40
MYM M41
MYM M42
MYM M43
MYM M44
MYM M45
MYM M46
MYM M50
MYM M51
MYM M52
MYM M53
MYM M56
MYM M57
MYM M6
MYM M7
MYM M8
MYM M9
MYM MOVIL M-00
MYM MOVIL M-03
MYM MOVIL M-04
MYM MOVIL M-04
MYM MOVIL M-05
MYM MOVIL M-06
MYM MOVIL M-07
MYM MOVIL M-08
MYM MOVIL M-09
MYM MOVIL M-10
MYM MOVIL M-11
MYM MOVIL M-12
MYM MOVIL M-13
MYM MOVIL M-14
MYM MOVIL M-15
MYM MOVIL M-16
MYM MOVIL M-17
MYM MOVIL M-18
MYM MOVIL M-19
MYM MOVIL M-20
MYM MOVIL M-21
MYM MOVIL M-22
MYM MOVIL M-23
MYM MOVIL M-24
MYM MOVIL M-25
MYM MOVIL M-26
MYM MOVIL M-27
MYM MOVIL M-28
MYM MOVIL M-29
NO DESEABLES
NO LOCALIZADOS
NO UBICADOS DIGITAL
OFFICER O1
OFFICER O10
OFFICER O11
OFFICER O12
OFFICER O13
OFFICER O14
OFFICER O15
OFFICER O16
OFFICER O17
OFFICER O18
OFFICER O19
OFFICER O2
OFFICER O3
OFFICER O4
OFFICER O5
OFFICER O6
OFFICER O7
OFFICER O8
OFFICER O9
PIRACY P1
PIRACY P2
PIRACY P3
PIRACY P4
PIRACY P5
PRUEBAS / DEMOS
PRUEBAS TIGO
RECUPERO VOLUNTARIO PYMES
SERVITEC (MOVILES)
SERVITEC MOVIL D-15
SERVITEC MOVIL D-15
SERVITEC MOVIL D-18
SERVITEC MOVIL D-19
SERVITEC MOVIL D-19
SERVITEC MOVIL D-22
SERVITEC MOVIL D-22
SERVITEC MOVIL D-24
SERVITEC MOVIL D-27
SERVITEC MOVIL D-30
SERVITEC MOVIL D-31
SERVITEC MOVIL D-33
SERVITEC MOVIL D-34
SERVITEC MOVIL D-38
SERVITEC MOVIL D-44
SERVITEC MOVIL SERVI-01
SERVITEC MOVIL SERVI-01
SERVITEC MOVIL SERVI-02
SERVITEC MOVIL SERVI-03
SERVITEC MOVIL SERVI-04
SERVITEC MOVIL SERVI-04
SERVITEC MOVIL SERVI-05
SERVITEC MOVIL SERVI-06
SERVITEC MOVIL SERVI-07
SERVITEC MOVIL SERVI-08
SERVITEC MOVIL SERVI-09
SERVITEC MOVIL SERVI-10
SERVITEC MOVIL SERVI-11
SERVITEC MOVIL SERVI-12
SERVITEC MOVIL SERVI-13
SERVITEC MOVIL SERVI-14
SERVITEC MOVIL SERVI-15
SERVITEC MOVIL SERVI-16
SERVITEC MOVIL SERVI-17
SERVITEC MOVIL SERVI-18
SERVITEC MOVIL SERVI-19
SERVITEC MOVIL SERVI-20
SERVITEC MOVIL SERVI-21
SERVITEC MOVIL SERVI-23
SERVITEC MOVIL SERVI-25
SERVITEC MOVIL SERVI-25
SERVITEC MOVIL SERVI-26
SERVITEC MOVIL SERVI-27
SERVITEC MOVIL SERVI-30
SERVITEC MOVIL SERVI-31
SERVITEC MOVIL SERVI-31
SERVITEC MOVIL SERVI-32
SERVITEC MOVIL SERVI-33
SERVITEC MOVIL SERVI-34
SERVITEC MOVIL SERVI-35
SERVITEC MOVIL SERVI-36
SERVITEC MOVIL SERVI-37
SERVITEC MOVIL SERVI-38
SERVITEC MOVIL SERVI-41
SERVITEC MOVIL SERVI-43
SERVITEC MOVIL SERVI-44
SERVITEC MOVIL SERVI-47
SETEO (MOVILES)
SETEO EQUIPO NO UTILIZABLE
SETEO EQUIPOS RACSA
SETEO M SUP 1
SETEO M SUP 2
SETEO M SUP 3
SETEO M SUP 4
SETEO M SUP 5
SETEO M SUP 6
SETEO M SUP 7
SETEO M1
SETEO M10
SETEO M100
SETEO M101
SETEO M102
SETEO M103
SETEO M104
SETEO M105
SETEO M106
SETEO M107
SETEO M108
SETEO M109
SETEO M11
SETEO M110
SETEO M111
SETEO M112
SETEO M113
SETEO M114
SETEO M115
SETEO M116
SETEO M117
SETEO M118
SETEO M119
SETEO M12
SETEO M120
SETEO M121
SETEO M122
SETEO M123
SETEO M124
SETEO M129
SETEO M13
SETEO M130
SETEO M131
SETEO M14
SETEO M15
SETEO M16
SETEO M17
SETEO M18
SETEO M19
SETEO M2
SETEO M20
SETEO M21
SETEO M22
SETEO M23
SETEO M24
SETEO M25
SETEO M26
SETEO M27
SETEO M28
SETEO M29
SETEO M3
SETEO M30
SETEO M31
SETEO M32
SETEO M33
SETEO M34
SETEO M35
SETEO M36
SETEO M37
SETEO M38
SETEO M39
SETEO M4
SETEO M40
SETEO M41
SETEO M42
SETEO M43
SETEO M44
SETEO M45
SETEO M46
SETEO M47
SETEO M48
SETEO M49
SETEO M5
SETEO M50
SETEO M51
SETEO M52
SETEO M53
SETEO M54
SETEO M55
SETEO M56
SETEO M57
SETEO M58
SETEO M59
SETEO M6
SETEO M60
SETEO M61
SETEO M62
SETEO M63
SETEO M64
SETEO M65
SETEO M66
SETEO M67
SETEO M68
SETEO M69
SETEO M7
SETEO M70
SETEO M71
SETEO M72
SETEO M73
SETEO M74
SETEO M75
SETEO M76
SETEO M77
SETEO M78
SETEO M79
SETEO M8
SETEO M80
SETEO M81
SETEO M82
SETEO M83
SETEO M84
SETEO M85
SETEO M86
SETEO M87
SETEO M88
SETEO M89
SETEO M9
SETEO M90
SETEO M91
SETEO M92
SETEO M93
SETEO M94
SETEO M95
SETEO M96
SETEO M97
SETEO M98
SETEO M99
SETEO MOVIL S-01
SETEO MOVIL S-02
SETEO MOVIL S-03
SETEO MOVIL S-04
SETEO MOVIL S-05
SETEO MOVIL S-06
SETEO MOVIL S-07
SETEO MOVIL S-08
SETEO MOVIL S-09
SETEO MOVIL S-10
SETEO MOVIL S-11
SETEO MOVIL S-12
SETEO MOVIL S-14
SETEO MOVIL S-15
SETEO MOVIL S-16
SETEO MOVIL S-17
SETEO MOVIL S-18
SETEO MOVIL S-19
SETEO MOVIL S-20
SETEO MOVIL S-21
SETEO MOVIL S-22
SETEO MOVIL S-26
SETEO MOVIL S-27
SETEO MOVIL S-30
SETEO MOVIL S-31
SETEO MOVIL S-32
SETEO MOVIL S-33
SETEO MOVIL S-35
SETEO MOVIL S-36
SETEO MOVIL S-37
SETEO MOVIL S-38
SETEO MOVIL S-39
SETEO MOVIL S-40
SETEO MOVIL S-41
SETEO MOVIL S-42
SETEO MOVIL S-43
SETEO MOVIL S-44
SETEO MOVIL S-45
SETEO MOVIL S-46
SETEO MOVIL S-47
SETEO MOVIL S-48
SETEO MOVIL S-50
SETEO MOVIL S-51
SOLFINSUR (MOVILES)
ST REDES (MOVILES)
ST REDES MOVIL D-01
ST REDES MOVIL D-01
ST REDES MOVIL D-02
ST REDES MOVIL D-03
ST REDES MOVIL D-03
ST REDES MOVIL D-04
ST REDES MOVIL D-05
ST REDES MOVIL D-06
ST REDES MOVIL D-07
ST REDES MOVIL D-08
ST REDES MOVIL D-09
ST REDES MOVIL D-10
ST REDES MOVIL D-11
ST REDES MOVIL D-12
ST REDES MOVIL D-13
ST REDES MOVIL D-14
ST REDES MOVIL D-16
ST REDES MOVIL D-17
ST REDES MOVIL D-20
ST REDES MOVIL G-01
ST REDES MOVIL G-02
ST REDES MOVIL P-01
ST REDES MOVIL P-02
SUPERVISOR S1
SUPERVISOR S2
SUPERVISOR S3
SWAT S1
SWAT S2
SWAT S3
SWAT S4
SWAT S5
SWAT S6
SWAT SUP MOVILES
TALLER TIGO
TECH PARTNER (MOVIL)
TECH PARTNER BODEGA
TECNI M SUP 1
TECNI M SUP 2
TECNI M SUP 3
TECNI MRG 01
TECNI MRG 02
TECNI MRG 03
TECNI MRG 04
TECNI MRG 05
TECNI MRG 09
TECNI MRG 13
TECNI MRG 14
TECNI MRG 19
TECNI MRG 21
TECNI MRG 23
TECNI MRG 26
TECNI MRG 28
TECNI MRP 01
TECNI MRP 02
TECNI MRP 03
TECNI MRP 04
TECNI MRP 05
TECNI MRP 07
TECNI MRP 18
TECNICOS AUDITORIA TIGO
TECNISERVICIOS (MOVILES)
TECNISERVICIOS MOVIL MDO-001
TECNISERVICIOS MOVIL MDO-001
TECNISERVICIOS MOVIL MDO-002
TECNISERVICIOS MOVIL MDO-002
TECNISERVICIOS MOVIL MDO-003
TECNISERVICIOS MOVIL MDO-004
TECNISERVICIOS MOVIL MDO-005 
TECNISERVICIOS MOVIL MDO-010 
TECNISERVICIOS MOVIL MDO-045 
TECNISERVICIOS MOVIL MDO-052 
TECNISERVICIOS MOVIL MDO-064 
TECNISERVICIOS MOVIL MDO-076 
TIGO APROVISIONAMIENTO
TIGO-01
TIGO-01
TIGO-02
TIGO-02
TIGO-03
TIGO-03
TIGO-04
TIGO-04
TIGO-05
TIGO-06
TIGO-07
TIGO-08
TIGO-09
TIGO-10
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0022W0008W0007CENTROSTOCKDESID&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0022W0008W0007CENTROSTOCKDESID']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='W0022W0008W0007TABLE2']/tbody/tr[2]/td[4]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destino'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BODEGA TIGO'])[3]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuarios'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuario'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/select</value>
   </webElementXpaths>
</WebElementEntity>
