<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AJUSTE CONVENIO AVALAJUSTE TARJETACH_f835a2</name>
   <tag></tag>
   <elementGuidId>d18c2285-8727-4bb4-9701-31efbf609554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'W0024W0007W0009CPGOTIPOID' and @name = 'W0024W0007W0009CPGOTIPOID']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0024W0007W0009CPGOTIPOID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0024W0007W0009CPGOTIPOID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0024W0007W0009CPGOTIPOID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 53,'W0024W0007W0009',false,'',0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.evt.onchange(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,53);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
AJUSTE CONVENIO AVALAJUSTE TARJETACHEQUECHEQUE DEVOLUCIÓNCOMISIONESCOMISIONES BANCARIASCONTRACARGOS TARJETASD-COMISIONESD-COMISIONES BANCARIASD-COMISIONES PAGADASD-DEPOSITOS DE MASD-DEVOLUCION DE DEPOSITOSD-DIFERENCIAL CAMBIARIO (+)D-DIFERENCIAL CAMBIARIO (-)D-FALTANTES CAJA &lt; 1000D-FALTANTES CAJA > 1000D-OTROS FALTANTESD-OTROS INGRESOSD-OTROS PENDIENTESD-OTROS SOBRANTESD-PAGO DE MAS TARJETASD-PAGO EN LINEAD-PAGOS AMSYSD-PAGOS CLIENTES EXTERNOSD-REDONDEO NEGATIVOD-REDONDEO POSITIVOD-SOBRANTES CAJA &lt; 1000D-SOBRANTES CAJA > 1000D-VALORES RECIBIDOS OTRAS OF.D-VENTAS ARTÍCULOSD-VENTAS PUBLICIDADDEBITODEPOSITODEPOSITOS DE MASDEVOLUCION DE DEPOSITOSE-AJUSTE CONVENIO AVALE-COMISIONESE-COMISIONES BANCARIASE-COMISIONES PAGADASE-DEPOSITOS DE MASE-DEVOLUCION DE DEPOSITOSE-DIFERENCIAL CAMBIARIO (+)E-DIFERENCIAL CAMBIARIO (-)E-FALTANTES CAJA &lt; 1000E-FALTANTES CAJA > 1000E-OTROS FALTANTESE-OTROS INGRESOSE-OTROS PENDIENTESE-OTROS SOBRANTESE-PAGO DE MAS TARJETASE-PAGO EN LINEAE-PAGOS AMSYSE-PAGOS CLIENTES EXTERNOSE-REDONDEO NEGATIVOE-REDONDEO POSITIVOE-SOBRANTES CAJA &lt; 1000E-SOBRANTES CAJA > 1000E-VALORES RECIBIDOS OTRAS OF.E-VENTAS ARTÍCULOSE-VENTAS PUBLICIDADEFECTIVOIVA POR COMISIÓNONLINEPAGO DE MAS TARJETASPAGO EN LINEAREDONDEO NEGATIVOREDONDEO POSITIVORETENCIONESTARJETATRANSFERENCIA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0024W0007W0009CPGOTIPOID&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0024W0007W0009CPGOTIPOID']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='W0024W0007W0009K2BTABLETABULARDATACAJAGRUPODIAVALOR']/tbody/tr[8]/td[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Pago'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pago Tipo'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='En Apertura de Caja?'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
