<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BAGO-CONSULTORIO MEDICO RUSIA18BANCO_8a34e1</name>
   <tag></tag>
   <elementGuidId>07d00a0b-850e-4add-b2bb-d936c6d92acb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'W0027W0007W0009CANALDEVENTAID' and @name = 'W0027W0007W0009CANALDEVENTAID' and (text() = '
BAGO-CONSULTORIO MEDICO RUSIA18BANCO SOL-SOL MUNDIALEROCALL MOBILECBN-EQUIPA TU LIVINGCOMPETENCIA_COMTECOCORPORATED2D G2M DIRD2D HOME DIRD2D HOME INDGRUPO PROMOTORMIGRACIONES_BRANDMIGRACION_MMDS_DTH_PREMIGRACION_MMDS_HFCMIG_DTH_POST_HFCMIG_DTH_PRE_HFCMIG_MMDS_ANA_DTH_POSTMIG_MMDS_ANA_DTH_PRMIG_MMDS_DIGI_DTH PREMIG_MMDS_DIGI_DTH_POSTMIG_WIMAX_HFCPDA G2M INDREAPERTURA_DE_CODIGOS_PREPAGORETAILSACTLV G2M DIRTLV HOME DIRVENTA NO PRESENCIAL' or . = '
BAGO-CONSULTORIO MEDICO RUSIA18BANCO SOL-SOL MUNDIALEROCALL MOBILECBN-EQUIPA TU LIVINGCOMPETENCIA_COMTECOCORPORATED2D G2M DIRD2D HOME DIRD2D HOME INDGRUPO PROMOTORMIGRACIONES_BRANDMIGRACION_MMDS_DTH_PREMIGRACION_MMDS_HFCMIG_DTH_POST_HFCMIG_DTH_PRE_HFCMIG_MMDS_ANA_DTH_POSTMIG_MMDS_ANA_DTH_PRMIG_MMDS_DIGI_DTH PREMIG_MMDS_DIGI_DTH_POSTMIG_WIMAX_HFCPDA G2M INDREAPERTURA_DE_CODIGOS_PREPAGORETAILSACTLV G2M DIRTLV HOME DIRVENTA NO PRESENCIAL')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0027W0007W0009CANALDEVENTAID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0027W0007W0009CANALDEVENTAID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 58,'W0027W0007W0009',false,'',0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.evt.onchange(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,58);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
BAGO-CONSULTORIO MEDICO RUSIA18BANCO SOL-SOL MUNDIALEROCALL MOBILECBN-EQUIPA TU LIVINGCOMPETENCIA_COMTECOCORPORATED2D G2M DIRD2D HOME DIRD2D HOME INDGRUPO PROMOTORMIGRACIONES_BRANDMIGRACION_MMDS_DTH_PREMIGRACION_MMDS_HFCMIG_DTH_POST_HFCMIG_DTH_PRE_HFCMIG_MMDS_ANA_DTH_POSTMIG_MMDS_ANA_DTH_PRMIG_MMDS_DIGI_DTH PREMIG_MMDS_DIGI_DTH_POSTMIG_WIMAX_HFCPDA G2M INDREAPERTURA_DE_CODIGOS_PREPAGORETAILSACTLV G2M DIRTLV HOME DIRVENTA NO PRESENCIAL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0027W0007W0009CANALDEVENTAID&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0027W0007W0009CANALDEVENTAID']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='W0027W0007W0009TABLE3']/tbody/tr[2]/td[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canal De Venta'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo de Preventa'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotor'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referente De Venta'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
