<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_100MB  12 MESES TRIAL100MB  6 MESES _fff5c2</name>
   <tag></tag>
   <elementGuidId>5e5cea51-df6b-4564-a148-fcafc4b2cce4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'W0024W0007W0009PRODUCTOPRDTEMPORALID' and @name = 'W0024W0007W0009PRODUCTOPRDTEMPORALID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0024W0007W0009PRODUCTOPRDTEMPORALID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0024W0007W0009PRODUCTOPRDTEMPORALID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 34,'W0024W0007W0009',false,'',0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.evt.onchange(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,34);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
100MB  12 MESES TRIAL100MB  6 MESES TRIAL100MB  MES TRIAL10MB 1 MES TRIAL10MB 12 MESES TRIAL10MB 3 MESES TRIAL10MB 6 MESES TRIAL10MB 9 MESES TRIAL12MB  12 MESES TRIAL12MB  6 MESES TRIAL12MB  MES TRIAL20MB 1 MES TRIAL20MB 12 MESES TRIAL20MB 3 MESES TRIAL20MB 6 MESES TRIAL20MB 9 MESES TRIAL25MB  12 MESES TRIAL25MB  6 MESES TRIAL25MB  MES TRIAL50MB  12 MESES TRIAL50MB  6 MESES TRIAL50MB  MES TRIAL5MB 1 MES TRIAL5MB 12 MESES TRIAL5MB 3 MESES TRIAL5MB 6 MESES TRIAL5MB 9 MESES TRIAL7.5MB 1 MES TRIAL7.5MB 12 MESES TRIAL7.5MB 3 MESES TRIAL7.5MB 6 MESES TRIAL7.5MB 9 MESES TRIAL8MB  12 MESES TRIAL8MB  6 MESES TRIAL8MB  MES TRIALINDEM MES GRATUITOINDEM_BOOST 3MB 12H COMPRAINDEM_BOOST 3MB 1D COMPRAINDEM_BOOST 3MB 1H TRIALINDEM_BOOST 3MB 1S COMPRAINDEM_BOOST 3MB 2D COMPRAINDEM_BOOST 3MB 2H TRIALINDEM_BOOST 3MB 3H TRIALINDEM_BOOST 3MB 5D COMPRAINDEM_BOOST 3MB 6H COMPRAINTERNET 10 MBPS IT NOWINTERNET 10MBPS TEMPORALINTERNET 2MBPS CORPORATIVOINTERNET DE 20 MB POR 15 DIASINTERNET JOSELYNSPB_BOOST 10MB 1H TRIALSPB_BOOST 10MB 2H TRIALSPB_BOOST 10MB 3H TRIALSPB_BOOST 12MB 1H TRIALSPB_BOOST 12MB 2H TRIALSPB_BOOST 12MB 3H TRIALSPB_BOOST 20MB 1H TRIALSPB_BOOST 20MB 1H TRIALSPB_BOOST 20MB 2H TRIALSPB_BOOST 20MB 2H TRIALSPB_BOOST 20MB 3H TRIALSPB_BOOST 20MB 3H TRIALSPB_BOOST 5MB 1H TRIALSPB_BOOST 5MB 2H TRIALSPB_BOOST 5MB 3H TRIALSPB_BOOST 8MB 1H TRIALSPB_BOOST 8MB 2H TRIALSPB_BOOST 8MB 3H TRIALSPB_BOOST IB522 a 3MB 1D COMPRASPB_BOOST IB522 a 3MB 1D COMPRASPB_BOOST IB522 a 3MB 1S COMPRASPB_BOOST IB522 a 3MB 1S COMPRASPB_BOOST IB522 a 3MB 2D COMPRASPB_BOOST IB522 a 3MB 2D COMPRASPB_BOOST IB522 a 3MB 2S COMPRASPB_BOOST IB522 a 3MB 2S COMPRASPB_BOOST IB522 a 3MB 3D COMPRASPB_BOOST IB522 a 3MB 3D COMPRASPB_BOOST IB522 a 3MB 4D COMPRASPB_BOOST IB522 a 3MB 4D COMPRASPB_BOOST IB522 a 3MB 5D COMPRASPB_BOOST IB522 a 3MB 5D COMPRASPB_BOOST IB522 a 5MB 1D COMPRASPB_BOOST IB522 a 5MB 1D COMPRASPB_BOOST IB522 a 5MB 1S COMPRASPB_BOOST IB522 a 5MB 1S COMPRASPB_BOOST IB522 a 5MB 2D COMPRASPB_BOOST IB522 a 5MB 2D COMPRASPB_BOOST IB522 a 5MB 2S COMPRASPB_BOOST IB522 a 5MB 2S COMPRASPB_BOOST IB522 a 5MB 3D COMPRASPB_BOOST IB522 a 5MB 3D COMPRASPB_BOOST IB522 a 5MB 4D COMPRASPB_BOOST IB522 a 5MB 4D COMPRASPB_BOOST IB522 a 5MB 5D COMPRASPB_BOOST IB522 a 5MB 5D COMPRASPB_BOOST ID3M2 a 5MB 1D COMPRASPB_BOOST ID3M2 a 5MB 1D COMPRASPB_BOOST ID3M2 a 5MB 1S COMPRASPB_BOOST ID3M2 a 5MB 1S COMPRASPB_BOOST ID3M2 a 5MB 2D COMPRASPB_BOOST ID3M2 a 5MB 2D COMPRASPB_BOOST ID3M2 a 5MB 2S COMPRASPB_BOOST ID3M2 a 5MB 2S COMPRASPB_BOOST ID3M2 a 5MB 3D COMPRASPB_BOOST ID3M2 a 5MB 3D COMPRASPB_BOOST ID3M2 a 5MB 4D COMPRASPB_BOOST ID3M2 a 5MB 4D COMPRASPB_BOOST ID3M2 a 5MB 5D COMPRASPB_BOOST ID3M2 a 5MB 5D COMPRASPB_BOOST ID3P1 a 5MB 1D COMPRASPB_BOOST ID3P1 a 5MB 1D COMPRASPB_BOOST ID3P1 a 5MB 1S COMPRASPB_BOOST ID3P1 a 5MB 1S COMPRASPB_BOOST ID3P1 a 5MB 2D COMPRASPB_BOOST ID3P1 a 5MB 2D COMPRASPB_BOOST ID3P1 a 5MB 2S COMPRASPB_BOOST ID3P1 a 5MB 2S COMPRASPB_BOOST ID3P1 a 5MB 3D COMPRASPB_BOOST ID3P1 a 5MB 3D COMPRASPB_BOOST ID3P1 a 5MB 4D COMPRASPB_BOOST ID3P1 a 5MB 4D COMPRASPB_BOOST ID3P1 a 5MB 5D COMPRASPB_BOOST ID3P1 a 5MB 5D COMPRASPB_BOOST IP2M2 a 4MB 1D COMPRASPB_BOOST IP2M2 a 4MB 1D COMPRASPB_BOOST IP2M2 a 4MB 1S COMPRASPB_BOOST IP2M2 a 4MB 1S COMPRASPB_BOOST IP2M2 a 4MB 2D COMPRASPB_BOOST IP2M2 a 4MB 2D COMPRASPB_BOOST IP2M2 a 4MB 2S COMPRASPB_BOOST IP2M2 a 4MB 2S COMPRASPB_BOOST IP2M2 a 4MB 3D COMPRASPB_BOOST IP2M2 a 4MB 3D COMPRASPB_BOOST IP2M2 a 4MB 4D COMPRASPB_BOOST IP2M2 a 4MB 4D COMPRASPB_BOOST IP2M2 a 4MB 5D COMPRASPB_BOOST IP2M2 a 4MB 5D COMPRASPB_BOOST IP2M2 a 5MB 1D COMPRASPB_BOOST IP2M2 a 5MB 1D COMPRASPB_BOOST IP2M2 a 5MB 1S COMPRASPB_BOOST IP2M2 a 5MB 1S COMPRASPB_BOOST IP2M2 a 5MB 2D COMPRASPB_BOOST IP2M2 a 5MB 2D COMPRASPB_BOOST IP2M2 a 5MB 2S COMPRASPB_BOOST IP2M2 a 5MB 2S COMPRASPB_BOOST IP2M2 a 5MB 3D COMPRASPB_BOOST IP2M2 a 5MB 3D COMPRASPB_BOOST IP2M2 a 5MB 4D COMPRASPB_BOOST IP2M2 a 5MB 4D COMPRASPB_BOOST IP2M2 a 5MB 5D COMPRASPB_BOOST IP2M2 a 5MB 5D COMPRASPB_BOOST IS1M2 a 3MB 1D COMPRASPB_BOOST IS1M2 a 3MB 1D COMPRASPB_BOOST IS1M2 a 3MB 1S COMPRASPB_BOOST IS1M2 a 3MB 1S COMPRASPB_BOOST IS1M2 a 3MB 2D COMPRASPB_BOOST IS1M2 a 3MB 2D COMPRASPB_BOOST IS1M2 a 3MB 2S COMPRASPB_BOOST IS1M2 a 3MB 2S COMPRASPB_BOOST IS1M2 a 3MB 3D COMPRASPB_BOOST IS1M2 a 3MB 3D COMPRASPB_BOOST IS1M2 a 3MB 4D COMPRASPB_BOOST IS1M2 a 3MB 4D COMPRASPB_BOOST IS1M2 a 3MB 5D COMPRASPB_BOOST IS1M2 a 3MB 5D COMPRASPB_BOOST IS1M2 a 5MB 1D COMPRASPB_BOOST IS1M2 a 5MB 1D COMPRASPB_BOOST IS1M2 a 5MB 1S COMPRASPB_BOOST IS1M2 a 5MB 1S COMPRASPB_BOOST IS1M2 a 5MB 2D COMPRASPB_BOOST IS1M2 a 5MB 2D COMPRASPB_BOOST IS1M2 a 5MB 2S COMPRASPB_BOOST IS1M2 a 5MB 2S COMPRASPB_BOOST IS1M2 a 5MB 3D COMPRASPB_BOOST IS1M2 a 5MB 3D COMPRASPB_BOOST IS1M2 a 5MB 4D COMPRASPB_BOOST IS1M2 a 5MB 4D COMPRASPB_BOOST IS1M2 a 5MB 5D COMPRASPB_BOOST IS1M2 a 5MB 5D COMPRASPB_BOOST MBS75  a 20MB 1D COMPRASPB_BOOST MBS75  a 20MB 1S COMPRASPB_BOOST MBS75  a 20MB 2D COMPRASPB_BOOST MBS75  a 20MB 2S COMPRASPB_BOOST MBS75  a 20MB 3D COMPRASPB_BOOST MBS75  a 20MB 4D COMPRASPB_BOOST MBS75  a 20MB 5D COMPRASPB_BOOST MBS75 a 20MB 1D COMPRASPB_BOOST MBS75 a 20MB 1D COMPRASPB_BOOST MBS75 a 20MB 1S COMPRASPB_BOOST MBS75 a 20MB 1S COMPRASPB_BOOST MBS75 a 20MB 2D COMPRASPB_BOOST MBS75 a 20MB 2D COMPRASPB_BOOST MBS75 a 20MB 2S COMPRASPB_BOOST MBS75 a 20MB 2S COMPRASPB_BOOST MBS75 a 20MB 3D COMPRASPB_BOOST MBS75 a 20MB 3D COMPRASPB_BOOST MBS75 a 20MB 4D COMPRASPB_BOOST MBS75 a 20MB 4D COMPRASPB_BOOST MBS75 a 20MB 5D COMPRASPB_BOOST MBS75 a 20MB 5D COMPRASPB_BOOST MEGA10 a 20MB 1D COMPRASPB_BOOST MEGA10 a 20MB 1D COMPRASPB_BOOST MEGA10 a 20MB 1S COMPRASPB_BOOST MEGA10 a 20MB 1S COMPRASPB_BOOST MEGA10 a 20MB 2D COMPRASPB_BOOST MEGA10 a 20MB 2D COMPRASPB_BOOST MEGA10 a 20MB 2S COMPRASPB_BOOST MEGA10 a 20MB 2S COMPRASPB_BOOST MEGA10 a 20MB 3D COMPRASPB_BOOST MEGA10 a 20MB 3D COMPRASPB_BOOST MEGA10 a 20MB 4D COMPRASPB_BOOST MEGA10 a 20MB 4D COMPRASPB_BOOST MEGA10 a 20MB 5D COMPRASPB_BOOST MEGA10 a 20MB 5D COMPRASPB_BOOST MEGA12 a 20MB 1D COMPRASPB_BOOST MEGA12 a 20MB 1S COMPRASPB_BOOST MEGA12 a 20MB 2D COMPRASPB_BOOST MEGA12 a 20MB 2S COMPRASPB_BOOST MEGA12 a 20MB 3D COMPRASPB_BOOST MEGA12 a 20MB 4D COMPRASPB_BOOST MEGA12 a 20MB 5D COMPRASPB_BOOST MEGA3 a 12MB 1D COMPRASPB_BOOST MEGA3 a 12MB 1S COMPRASPB_BOOST MEGA3 a 12MB 2D COMPRASPB_BOOST MEGA3 a 12MB 2S COMPRASPB_BOOST MEGA3 a 12MB 3D COMPRASPB_BOOST MEGA3 a 12MB 4D COMPRASPB_BOOST MEGA3 a 12MB 5D COMPRASPB_BOOST MEGA4 a 12MB 1D COMPRASPB_BOOST MEGA4 a 12MB 1S COMPRASPB_BOOST MEGA4 a 12MB 2D COMPRASPB_BOOST MEGA4 a 12MB 2S COMPRASPB_BOOST MEGA4 a 12MB 3D COMPRASPB_BOOST MEGA4 a 12MB 4D COMPRASPB_BOOST MEGA4 a 12MB 5D COMPRASPB_BOOST MEGA5 a 12MB 1D COMPRASPB_BOOST MEGA5 a 12MB 1S COMPRASPB_BOOST MEGA5 a 12MB 2D COMPRASPB_BOOST MEGA5 a 12MB 2S COMPRASPB_BOOST MEGA5 a 12MB 3D COMPRASPB_BOOST MEGA5 a 12MB 4D COMPRASPB_BOOST MEGA5 a 12MB 5D COMPRASPB_BOOST MEGA8 a 20MB 1D COMPRASPB_BOOST MEGA8 a 20MB 1S COMPRASPB_BOOST MEGA8 a 20MB 2D COMPRASPB_BOOST MEGA8 a 20MB 2S COMPRASPB_BOOST MEGA8 a 20MB 3D COMPRASPB_BOOST MEGA8 a 20MB 4D COMPRASPB_BOOST MEGA8 a 20MB 5D COMPRAYVSGVRATAGLJIQMMCMKC</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0024W0007W0009PRODUCTOPRDTEMPORALID&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0024W0007W0009PRODUCTOPRDTEMPORALID']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='W0024W0007W0009TABLE2']/tbody/tr[3]/td[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producto Temporal'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SERVICIO BASICO'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COSTA RICA'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferencias de usuario'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
