<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Seleccionar Contrato de Cliente_gx-mask</name>
   <tag></tag>
   <elementGuidId>2dccd589-0fb2-48f0-b90c-5bcf95ae03c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.gx-mask</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gx-mask</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;Form Form-fx gx-masked-relative gx-masked&quot;]/div[@class=&quot;gx-mask&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div[4]</value>
   </webElementXpaths>
</WebElementEntity>
